# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ompWrite <- function(objs, paths) {
    invisible(.Call('RReadWriteBigDataFrame_ompWrite', PACKAGE = 'RReadWriteBigDataFrame', objs, paths))
}

ompRead <- function(paths) {
    .Call('RReadWriteBigDataFrame_ompRead', PACKAGE = 'RReadWriteBigDataFrame', paths)
}

#'@export
readSingle <- function(path) {
    .Call('RReadWriteBigDataFrame_readSingle', PACKAGE = 'RReadWriteBigDataFrame', path)
}

