# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ompWrite <- function(objs, paths) {
    invisible(.Call('RSaveBigObj_ompWrite', PACKAGE = 'RSaveBigObj', objs, paths))
}

ompRead <- function(paths) {
    .Call('RSaveBigObj_ompRead', PACKAGE = 'RSaveBigObj', paths)
}

